### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by HabibRh26** [Chintan2108/CHEERBOT-Your-Emotional-Companion#5]
I want to know your planning regarding the further procedure of this project meaning - what are the technologies needed to contribute like python frontend ,backend or other stuffs etc. Based on which I may apply through SLoP program. Thanks

**Comment by Chintan2108** [comment]
There are three major tasks:
1. Develop a single page web-app with chat interface suitable for both computers and mobiles (responsive). 
2. Deploy this web-app on GCP (and hence I would prefer PHP, but open to other stack as well) with the Cheerbot in the backend, so that there is a proper interface of interacting with Cheerbot.
3. Perform Voice Pitch Analysis to determine if the user is sad when he chooses an audio input method.

Techstack for the same is:
- Python 3.x; libraries: pyaudio, pygame, pywave
- PHP/HTML/CSS/Bootstrap (open to other stack/servers as well)

Please let me know if you have any queries.

**Comment by HabibRh26** [comment]
thanks for the clear explanation.
